title: Erik Passos
description: Blog sobre diversos temas, com um foco em Tecnologia, programação, web, iot, desktop, hardware, nuvem, computação, carreira, emprego, vagas, ti, informática, cursos, certificados, php, html5, css3, java, javascript, typescript, nodejs, ionic, android, ios, linux, macos, windows, salvador, bahia, brasil, livros, politica, redes sociais, facebook, instagram, twitter, google, blogs, ensino publico, sino de ti.

url: https://erikpassos.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: https://github.com/ErikPassos
   twitter: https://twitter.com/ErikPassos7
   facebook: https://www.facebook.com/erik.fernando.96
   email: brimaidesigns@gmail.com

google_analytics: "Google"
